<div class="box contact">

    <form id="contact_form" name="contact_form" action="<?php echo $this->getUrl('contact/') ?>index/sendemail" method="post">

        <fieldset class="group-select">
            <h4 class="legend">Mad_Contact module sample</h4>
            <ul>
                <li>
                    <div class="input-box">
                        <label for="name">Gimme your name <span class="required">*</span></label><br />

                        <input name="name" id="name" title="Name" value="" class="required-entry input-text" type="text" />
                    </div>

                    <div class="input-box">
                        <label for="email">And your email <span class="required">*</span></label><br />
                        <input name="email" id="email" title="Email" value="" class="required-entry input-text validate-email" type="text" />
                    </div>

                    <div class="clear"></div>

                    <div class="input-box">
                        &nbsp;        <label for="comment">Some comment?</label><br />

                        <textarea name="comment" id="comment" title="Comment" class="required-entry input-text" style="height:100px;" cols="50" rows="3"></textarea>
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="button-set">
            <p class="required">* Required Fields</p>
            <button class="form-button" type="submit"><span>Submit</span></button>

        </div>
    </form>

</div>
