<div class="form_mini">
    <div class="form_head">
        <span><?php echo Mage::helper('contacts')->__('Call back') ?></span>
    </div>

    <form id="contactForm" name="contact_form" action="<?php echo $this->getUrl('contact/') ?>index/post" method="post">
        <div class="form_content">
            <input name="name" id="name"
                   title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>"
                   value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>"
                   placeholder="<?php echo Mage::helper('contacts')->__('Имя*') ?>"
                   class="name required-entry" type="text"/>
            <input name="email" id="email"
                   title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>"
                   value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>"
                   placeholder="<?php echo Mage::helper('contacts')->__('E-mail') ?>"
                   class="email validate-email" type="text"/>
            <input name="telephone" id="telephone"
                   title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>"
                   value=""
                   placeholder="<?php echo Mage::helper('contacts')->__('Моб. телефон*: +380XXXXXXXXX') ?>"
                   class="telefon required-entry" type="text"/>
        </div>
        <div class="form_button">
            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;"/>
            <?php echo $this->getBlockHtml('formkey') ?>
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button">
                <span><?php echo Mage::helper('contacts')->__('Заказать звонок') ?></span></button>
        </div>
    </form>
</div>
<script type="text/javascript">
    //<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
    //]]>
</script>
